---

- name: Install apt-cache-ng
  hosts: cachers
  become: yes
  gather_facts: False
  pre_tasks:
    - name: install python 2
      gather_facts: no
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

          

  roles:
    - ansible-apt-cacher-ng

