---
- name: Gathering facts
  setup:
  
- name: Install Apt-cacher-ng
  apt: 
    name: apt-cacher-ng
    state: present
    update_cache: yes

- name: Enable systemd service
  ansible.builtin.systemd:
    name: apt-cacher-ng
    enabled: yes

- name: Copying configs
  copy:
    src: acng.conf
    dest: /etc/apt-cacher-ng/acng.conf
    owner: root
    group: root
    mode: 0644

- name: update and upgrade
  become: true
  apt:
    update_cache: yes
    upgrade: yes 

- name: Reloading services
  ansible.builtin.systemd:
    name: apt-cacher-ng
    state: reloaded
